[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
    "num2words>=0.5.14",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
